# Generated by Django 5.1.7 on 2025-03-15 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_expiration_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='expiration_day',
            new_name='expire_at',
        ),
    ]
